
# load in the data

files <- list.files('./../R/win-library/4.1/ukghg/extdata/', full.names = T)

c2h6BySector_LonLat_0.01deg.grd <- raster::stack(files[1])
c2h6BySector_LonLat_0.01deg.gri<- raster::stack(files[2])
c2h6BySector_OSGB_100km.grd <- raster::stack(files[3])
c2h6BySector_OSGB_100km.gri<- raster::stack(files[4])
c2h6BySector_OSGB_1km.grd <- raster::stack(files[5])
c2h6BySector_OSGB_1km.gri<- raster::stack(files[6])
c2h6BySector_OSGB_20km.grd <- raster::stack(files[7])
c2h6BySector_OSGB_20km.gri<- raster::stack(files[8])
ch4BySector_LonLat_0.01deg.grd <- raster::stack(files[9])
ch4BySector_LonLat_0.01deg.gri<- raster::stack(files[10])
ch4BySector_OSGB_100km.grd <- raster::stack(files[11])
ch4BySector_OSGB_100km.gri<- raster::stack(files[12])
ch4BySector_OSGB_1km.grd <- raster::stack(files[13])
ch4BySector_OSGB_1km.gri<- raster::stack(files[14])
ch4BySector_OSGB_20km.grd <- raster::stack(files[15])
ch4BySector_OSGB_20km.gri<- raster::stack(files[16])
co2BySector_LonLat_0.01deg.grd <- raster::stack(files[17])
co2BySector_LonLat_0.01deg.gri<- raster::stack(files[18])
co2BySector_OSGB_100km.grd <- raster::stack(files[19])
co2BySector_OSGB_100km.gri<- raster::stack(files[20])
co2BySector_OSGB_1km.grd <- raster::stack(files[21])
co2BySector_OSGB_1km.gri<- raster::stack(files[22])
co2BySector_OSGB_20km.grd <- raster::stack(files[23])
co2BySector_OSGB_20km.gri<- raster::stack(files[24])
Fch4_mean_Tgkm2y_LonLat_0.01deg.grd <- raster::raster(files[25])
Fch4_mean_Tgkm2y_LonLat_0.01deg.gri<- raster::raster(files[26])
Fch4_mean_Tgkm2y_OSGB_100km.grd <- raster::raster(files[27])
Fch4_mean_Tgkm2y_OSGB_100km.gri<- raster::raster(files[28])
Fch4_mean_Tgkm2y_OSGB_1km.grd <- raster::raster(files[29])
Fch4_mean_Tgkm2y_OSGB_1km.gri<- raster::raster(files[30])
Fch4_mean_Tgkm2y_OSGB_20km.grd <- raster::raster(files[31])
Fch4_mean_Tgkm2y_OSGB_20km.gri<- raster::raster(files[32])
lai_LonLat_0.01deg.grd <- raster::raster(files[33])
lai_LonLat_0.01deg.gri<- raster::raster(files[34])
lai_OSGB_100km.grd <- raster::raster(files[35])
lai_OSGB_100km.gri<- raster::raster(files[36])
lai_OSGB_1km.grd <- raster::raster(files[37])
lai_OSGB_1km.gri<- raster::raster(files[38])
lai_OSGB_20km.grd <- raster::raster(files[39])
lai_OSGB_20km.gri<- raster::raster(files[40])
n2oBySector_LonLat_0.01deg.grd <- raster::stack(files[41])
n2oBySector_LonLat_0.01deg.gri<- raster::stack(files[42])
n2oBySector_OSGB_100km.grd <- raster::stack(files[43])
n2oBySector_OSGB_100km.gri<- raster::stack(files[44])
n2oBySector_OSGB_1km.grd <- raster::stack(files[45])
n2oBySector_OSGB_1km.gri<- raster::stack(files[46])
n2oBySector_OSGB_20km.grd <- raster::stack(files[47])
n2oBySector_OSGB_20km.gri<- raster::stack(files[48])
vocBySector_LonLat_0.01deg.grd <- raster::stack(files[49])
vocBySector_LonLat_0.01deg.gri<- raster::stack(files[50])
vocBySector_OSGB_100km.grd <- raster::stack(files[51])
vocBySector_OSGB_100km.gri<- raster::stack(files[52])
vocBySector_OSGB_1km.grd <- raster::stack(files[53])
vocBySector_OSGB_1km.gri<- raster::stack(files[54])
vocBySector_OSGB_20km.grd <- raster::stack(files[55])
vocBySector_OSGB_20km.gri<- raster::stack(files[56])

##

usethis::use_data(c2h6BySector_LonLat_0.01deg.grd, overwrite = T)
usethis::use_data(c2h6BySector_LonLat_0.01deg.gri, overwrite = T)
usethis::use_data(c2h6BySector_OSGB_100km.grd, overwrite = T)
usethis::use_data(c2h6BySector_OSGB_100km.gri, overwrite = T)
usethis::use_data(c2h6BySector_OSGB_1km.grd, overwrite = T)
usethis::use_data(c2h6BySector_OSGB_1km.gri, overwrite = T)
usethis::use_data(c2h6BySector_OSGB_20km.grd, overwrite = T)
usethis::use_data(c2h6BySector_OSGB_20km.gri, overwrite = T)
usethis::use_data(ch4BySector_LonLat_0.01deg.grd, overwrite = T)
usethis::use_data(ch4BySector_LonLat_0.01deg.gri, overwrite = T)
usethis::use_data(ch4BySector_OSGB_100km.grd, overwrite = T)
usethis::use_data(ch4BySector_OSGB_100km.gri, overwrite = T)
usethis::use_data(ch4BySector_OSGB_1km.grd, overwrite = T)
usethis::use_data(ch4BySector_OSGB_1km.gri, overwrite = T)
usethis::use_data(ch4BySector_OSGB_20km.grd, overwrite = T)
usethis::use_data(ch4BySector_OSGB_20km.gri, overwrite = T)
usethis::use_data(co2BySector_LonLat_0.01deg.grd, overwrite = T)
usethis::use_data(co2BySector_LonLat_0.01deg.gri, overwrite = T)
usethis::use_data(co2BySector_OSGB_100km.grd, overwrite = T)
usethis::use_data(co2BySector_OSGB_100km.gri, overwrite = T)
usethis::use_data(co2BySector_OSGB_1km.grd, overwrite = T)
usethis::use_data(co2BySector_OSGB_1km.gri, overwrite = T)
usethis::use_data(co2BySector_OSGB_20km.grd, overwrite = T)
usethis::use_data(co2BySector_OSGB_20km.gri, overwrite = T)
usethis::use_data(Fch4_mean_Tgkm2y_LonLat_0.01deg.grd, overwrite = T)
usethis::use_data(Fch4_mean_Tgkm2y_LonLat_0.01deg.gri, overwrite = T)
usethis::use_data(Fch4_mean_Tgkm2y_OSGB_100km.grd, overwrite = T)
usethis::use_data(Fch4_mean_Tgkm2y_OSGB_100km.gri, overwrite = T)
usethis::use_data(Fch4_mean_Tgkm2y_OSGB_1km.grd, overwrite = T)
usethis::use_data(Fch4_mean_Tgkm2y_OSGB_1km.gri, overwrite = T)
usethis::use_data(Fch4_mean_Tgkm2y_OSGB_20km.grd, overwrite = T)
usethis::use_data(Fch4_mean_Tgkm2y_OSGB_20km.gri, overwrite = T)
usethis::use_data(lai_LonLat_0.01deg.grd, overwrite = T)
usethis::use_data(lai_LonLat_0.01deg.gri, overwrite = T)
usethis::use_data(lai_OSGB_100km.grd, overwrite = T)
usethis::use_data(lai_OSGB_100km.gri, overwrite = T)
usethis::use_data(lai_OSGB_1km.grd, overwrite = T)
usethis::use_data(lai_OSGB_1km.gri, overwrite = T)
usethis::use_data(lai_OSGB_20km.grd, overwrite = T)
usethis::use_data(lai_OSGB_20km.gri, overwrite = T)
usethis::use_data(n2oBySector_LonLat_0.01deg.grd, overwrite = T)
usethis::use_data(n2oBySector_LonLat_0.01deg.gri, overwrite = T)
usethis::use_data(n2oBySector_OSGB_100km.grd, overwrite = T)
usethis::use_data(n2oBySector_OSGB_100km.gri, overwrite = T)
usethis::use_data(n2oBySector_OSGB_1km.grd, overwrite = T)
usethis::use_data(n2oBySector_OSGB_1km.gri, overwrite = T)
usethis::use_data(n2oBySector_OSGB_20km.grd, overwrite = T)
usethis::use_data(n2oBySector_OSGB_20km.gri, overwrite = T)
usethis::use_data(vocBySector_LonLat_0.01deg.grd, overwrite = T)
usethis::use_data(vocBySector_LonLat_0.01deg.gri, overwrite = T)
usethis::use_data(vocBySector_OSGB_100km.grd, overwrite = T)
usethis::use_data(vocBySector_OSGB_100km.gri, overwrite = T)
usethis::use_data(vocBySector_OSGB_1km.grd, overwrite = T)
usethis::use_data(vocBySector_OSGB_1km.gri, overwrite = T)
usethis::use_data(vocBySector_OSGB_20km.grd, overwrite = T)
usethis::use_data(vocBySector_OSGB_20km.gri, overwrite = T)

# End
